# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: BackEnd CI

on: [push, pull_request_target]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    defaults:
      run:
        working-directory: backend

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm run test
        env:
          CI_DB_HOST: ${{ secrets.CI_DB_HOST }}
          CI_DB_NAME: ${{ secrets.CI_DB_NAME }}
          CI_DB_PASSWORD: ${{ secrets.CI_DB_PASSWORD }}
          CI_DB_USERNAME: ${{ secrets.CI_DB_USERNAME }}
          CLIENT_ID_GITHUB: ${{ secrets.APP_CLIENT_ID }}
          CLIENT_SECRET_GITHUB: ${{ secrets.APP_CLIENT_SECRET }}
